// Generates src/data/playoffs.generated.ts from data/nba/*.json and data/ucl/*.json.
// Run via `npm run gen:data` (invoked automatically by dev/build).
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'src', 'data', 'playoffs.generated.ts');

function loadLeague(name) {
  const dir = join(__dirname, '..', 'data', name);
  if (!existsSync(dir)) {
    console.error(`[gen:data] source dir not found: ${dir}`);
    process.exit(1);
  }
  return readdirSync(dir)
    .filter((f) => /^\d{4}\.json$/.test(f))
    .sort()
    .map((f) => JSON.parse(readFileSync(join(dir, f), 'utf8')));
}

const nba = loadLeague('nba');
const ucl = loadLeague('ucl');

const header = `// AUTO-GENERATED by scripts/gen-data.mjs — do not edit by hand.
import type { Playoffs } from '../types';

export const LEAGUES: { readonly nba: readonly Playoffs[]; readonly ucl: readonly Playoffs[] } = {
  nba: ${JSON.stringify(nba, null, 2)},
  ucl: ${JSON.stringify(ucl, null, 2)},
} as const;
`;

writeFileSync(OUT, header);
const count = (arr) => arr.reduce((n, y) => n + y.rounds.reduce((m, r) => m + r.series.length, 0), 0);
console.log(`[gen:data] wrote nba ${nba.length} seasons/${count(nba)} series, ucl ${ucl.length} seasons/${count(ucl)} series -> ${OUT}`);
