export const PASSPORT_LOCALITIES = [
  'Tel Aviv',
  'Jerusalem',
  'Haifa',
  'Rishon LeZion',
  'Petah Tikva',
  'Netanya',
  'Ashdod',
  'Beer Sheva',
  'Holon-Bat Yam',
  'Rehovot',
  'Kfar Saba-Raanana',
  'Modiin',
  'Ashkelon',
  'Nazareth',
  'Afula',
  'Acre-Nahariya',
  'Tiberias',
  'Eilat',
] as const;
