export const SCORES_365_API_URL = 'https://webws.365scores.com/web';

export const COMPETITION_IDS_MAP = {
  LIGAT_HAAL: 42,
  CHAMPIONS_LEAGUE: 572,
  EUROPA_LEAGUE: 573,
  PREMIER_LEAGUE: 7,
  LA_LIGA: 11,
  BUNDESLIGA: 25,
  SERIE_A: 17,
  WORLD_CUP: 5930,
  EURO: 6316,
};
export const COMPETITION_IDS = Object.values(COMPETITION_IDS_MAP);

export const COMPETITION_LOGOS_MAP = {
  [COMPETITION_IDS_MAP.LIGAT_HAAL]: '🇮🇱',
  [COMPETITION_IDS_MAP.CHAMPIONS_LEAGUE]: '🏆',
  [COMPETITION_IDS_MAP.EUROPA_LEAGUE]: '🇪🇺',
  [COMPETITION_IDS_MAP.PREMIER_LEAGUE]: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  [COMPETITION_IDS_MAP.LA_LIGA]: '🇪🇸',
  [COMPETITION_IDS_MAP.SERIE_A]: '🇮🇹',
  [COMPETITION_IDS_MAP.BUNDESLIGA]: '🇩🇪',
  [COMPETITION_IDS_MAP.WORLD_CUP]: '🌍',
  [COMPETITION_IDS_MAP.EURO]: '🇪🇺',
};
