// Generates src/data/playoffs.generated.ts from data/{nba,ucl,wc,euro}/*.json.
// Run via `npm run gen:data` (invoked automatically by dev/build).
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'src', 'data', 'playoffs.generated.ts');

const LEAGUE_IDS = ['nba', 'ucl', 'wc', 'euro'];

function loadLeague(name) {
  const dir = join(__dirname, '..', 'data', name);
  if (!existsSync(dir)) {
    console.error(`[gen:data] source dir not found: ${dir}`);
    process.exit(1);
  }
  return readdirSync(dir)
    .filter((f) => /^\d{4}\.json$/.test(f))
    .sort()
    .map((f) => JSON.parse(readFileSync(join(dir, f), 'utf8')));
}

const data = Object.fromEntries(LEAGUE_IDS.map((id) => [id, loadLeague(id)]));

const typeLine = LEAGUE_IDS.map((id) => `readonly ${id}: readonly Playoffs[]`).join('; ');
const bodyLines = LEAGUE_IDS.map((id) => `  ${id}: ${JSON.stringify(data[id], null, 2)},`).join('\n');

const header = `// AUTO-GENERATED by scripts/gen-data.mjs — do not edit by hand.
import type { Playoffs } from '../types';

export const LEAGUES: { ${typeLine} } = {
${bodyLines}
} as const;
`;

writeFileSync(OUT, header);
const count = (arr) => arr.reduce((n, y) => n + y.rounds.reduce((m, r) => m + r.series.length, 0), 0);
const summary = LEAGUE_IDS.map((id) => `${id} ${data[id].length}s/${count(data[id])}m`).join(', ');
console.log(`[gen:data] wrote ${summary} -> ${OUT}`);
