import bobcatsLogo from '../assets/logos/charlotte-bobcats.png';
import kcKingsLogo from '../assets/logos/kansas-city-kings.png';
import noHornetsLogo from '../assets/logos/new-orleans-hornets.png';
import sonicsLogo from '../assets/logos/seattle-supersonics.png';
import bulletsLogo from '../assets/logos/washington-bullets.png';
import type { League } from '../types';

export type TeamStyle = {
  readonly abbr: string;
  readonly primary: string;
  readonly secondary: string;
  readonly text: string; // best contrast text color on primary
};

const W = '#FFFFFF';

// Keyed by the exact full team name used in the playoff data (includes historical franchises).
export const TEAM_STYLES: Record<string, TeamStyle> = {
  'Atlanta Hawks': { abbr: 'ATL', primary: '#E03A3E', secondary: '#C1D32F', text: W },
  'Boston Celtics': { abbr: 'BOS', primary: '#007A33', secondary: '#BA9653', text: W },
  'Brooklyn Nets': { abbr: 'BKN', primary: '#000000', secondary: '#FFFFFF', text: W },
  'Charlotte Bobcats': { abbr: 'CHA', primary: '#F26432', secondary: '#2A5B83', text: W },
  'Charlotte Hornets': { abbr: 'CHA', primary: '#1D1160', secondary: '#00788C', text: W },
  'Chicago Bulls': { abbr: 'CHI', primary: '#CE1141', secondary: '#000000', text: W },
  'Cleveland Cavaliers': { abbr: 'CLE', primary: '#860038', secondary: '#FDBB30', text: W },
  'Dallas Mavericks': { abbr: 'DAL', primary: '#00538C', secondary: '#B8C4CA', text: W },
  'Denver Nuggets': { abbr: 'DEN', primary: '#0E2240', secondary: '#FEC524', text: W },
  'Detroit Pistons': { abbr: 'DET', primary: '#C8102E', secondary: '#1D42BA', text: W },
  'Golden State Warriors': { abbr: 'GSW', primary: '#1D428A', secondary: '#FFC72C', text: W },
  'Houston Rockets': { abbr: 'HOU', primary: '#CE1141', secondary: '#000000', text: W },
  'Indiana Pacers': { abbr: 'IND', primary: '#002D62', secondary: '#FDBB30', text: W },
  'Kansas City Kings': { abbr: 'KCK', primary: '#5A2D81', secondary: '#63727A', text: W },
  'Los Angeles Clippers': { abbr: 'LAC', primary: '#C8102E', secondary: '#1D428A', text: W },
  'Los Angeles Lakers': { abbr: 'LAL', primary: '#552583', secondary: '#FDB927', text: W },
  'Memphis Grizzlies': { abbr: 'MEM', primary: '#5D76A9', secondary: '#12173F', text: W },
  'Miami Heat': { abbr: 'MIA', primary: '#98002E', secondary: '#F9A01B', text: W },
  'Milwaukee Bucks': { abbr: 'MIL', primary: '#00471B', secondary: '#EEE1C6', text: W },
  'Minnesota Timberwolves': { abbr: 'MIN', primary: '#0C2340', secondary: '#236192', text: W },
  'New Jersey Nets': { abbr: 'NJN', primary: '#002A60', secondary: '#CD1041', text: W },
  'New Orleans Hornets': { abbr: 'NOH', primary: '#0A2240', secondary: '#1DA79E', text: W },
  'New Orleans Pelicans': { abbr: 'NOP', primary: '#0C2340', secondary: '#C8102E', text: W },
  'New York Knicks': { abbr: 'NYK', primary: '#006BB6', secondary: '#F58426', text: W },
  'Oklahoma City Thunder': { abbr: 'OKC', primary: '#007AC1', secondary: '#EF3B24', text: W },
  'Orlando Magic': { abbr: 'ORL', primary: '#0077C0', secondary: '#C4CED4', text: W },
  'Philadelphia 76ers': { abbr: 'PHI', primary: '#006BB6', secondary: '#ED174C', text: W },
  'Phoenix Suns': { abbr: 'PHX', primary: '#1D1160', secondary: '#E56020', text: W },
  'Portland Trail Blazers': { abbr: 'POR', primary: '#E03A3E', secondary: '#000000', text: W },
  'Sacramento Kings': { abbr: 'SAC', primary: '#5A2D81', secondary: '#63727A', text: W },
  'San Antonio Spurs': { abbr: 'SAS', primary: '#000000', secondary: '#C4CED4', text: W },
  'Seattle SuperSonics': { abbr: 'SEA', primary: '#006B3C', secondary: '#FFC72C', text: W },
  'Toronto Raptors': { abbr: 'TOR', primary: '#CE1141', secondary: '#000000', text: W },
  'Utah Jazz': { abbr: 'UTA', primary: '#002B5C', secondary: '#00471B', text: W },
  'Washington Bullets': { abbr: 'WSB', primary: '#002B5C', secondary: '#E31837', text: W },
  'Washington Wizards': { abbr: 'WAS', primary: '#002B5C', secondary: '#E31837', text: W },
};

// UEFA Champions League clubs (incl. historical names). Colors approximate club crests.
export const FOOTBALL_STYLES: Record<string, TeamStyle> = {
  'AC Milan': { abbr: 'MIL', primary: '#FB090B', secondary: '#000000', text: W },
  APOEL: { abbr: 'APO', primary: '#F8B300', secondary: '#003DA5', text: '#003DA5' },
  Aberdeen: { abbr: 'ABE', primary: '#E20E0E', secondary: '#FFFFFF', text: W },
  Ajax: { abbr: 'AJA', primary: '#D2122E', secondary: '#FFFFFF', text: W },
  Anderlecht: { abbr: 'AND', primary: '#582C83', secondary: '#FFFFFF', text: W },
  Arsenal: { abbr: 'ARS', primary: '#EF0107', secondary: '#063672', text: W },
  'Aston Villa': { abbr: 'AVL', primary: '#670E36', secondary: '#95BFE5', text: W },
  Atalanta: { abbr: 'ATA', primary: '#1E71B8', secondary: '#000000', text: W },
  'Atlético Madrid': { abbr: 'ATM', primary: '#CB3524', secondary: '#272E61', text: W },
  'Austria Wien': { abbr: 'AUW', primary: '#5C2482', secondary: '#FFFFFF', text: W },
  Auxerre: { abbr: 'AUX', primary: '#0055A4', secondary: '#FFFFFF', text: W },
  'BFC Dynamo': { abbr: 'BFC', primary: '#8B1A1A', secondary: '#F4C430', text: W },
  'Baník Ostrava': { abbr: 'BAN', primary: '#005BAC', secondary: '#FFFFFF', text: W },
  Barcelona: { abbr: 'BAR', primary: '#A50044', secondary: '#004D98', text: W },
  Basel: { abbr: 'BAS', primary: '#E30613', secondary: '#003DA5', text: W },
  'Bayer Leverkusen': { abbr: 'B04', primary: '#E32221', secondary: '#000000', text: W },
  'Bayern Munich': { abbr: 'BAY', primary: '#DC052D', secondary: '#0066B2', text: W },
  Benfica: { abbr: 'BEN', primary: '#E00034', secondary: '#FFFFFF', text: W },
  Beşiktaş: { abbr: 'BJK', primary: '#000000', secondary: '#FFFFFF', text: W },
  'Bodø/Glimt': { abbr: 'BOD', primary: '#FCD200', secondary: '#000000', text: '#000000' },
  Bordeaux: { abbr: 'BOR', primary: '#0A0A0A', secondary: '#00296B', text: W },
  'Borussia Dortmund': { abbr: 'BVB', primary: '#FDE100', secondary: '#000000', text: '#000000' },
  'Borussia Mönchengladbach': { abbr: 'BMG', primary: '#000000', secondary: '#00A650', text: W },
  Brøndby: { abbr: 'BRO', primary: '#004B9F', secondary: '#FFDE00', text: W },
  'CSKA Moscow': { abbr: 'CSK', primary: '#003D7C', secondary: '#DA291C', text: W },
  'CSKA Sofia': { abbr: 'CSS', primary: '#A50021', secondary: '#003DA5', text: W },
  'Celta Vigo': { abbr: 'CEL', primary: '#8AC3EE', secondary: '#E5231B', text: '#003DA5' },
  Celtic: { abbr: 'CEL', primary: '#018749', secondary: '#FFFFFF', text: W },
  Chelsea: { abbr: 'CHE', primary: '#034694', secondary: '#FFFFFF', text: W },
  'Club Brugge': { abbr: 'CLB', primary: '#005CA9', secondary: '#000000', text: W },
  Copenhagen: { abbr: 'FCK', primary: '#122A5B', secondary: '#FFFFFF', text: W },
  'Deportivo La Coruña': { abbr: 'DEP', primary: '#0067B1', secondary: '#FFFFFF', text: W },
  'Dinamo București': { abbr: 'DIN', primary: '#E30613', secondary: '#003DA5', text: W },
  'Dinamo Minsk': { abbr: 'DMI', primary: '#00509E', secondary: '#FFFFFF', text: W },
  Dnipro: { abbr: 'DNI', primary: '#003DA5', secondary: '#FFFFFF', text: W },
  'Dundee United': { abbr: 'DUN', primary: '#FF6600', secondary: '#000000', text: W },
  'Dynamo Dresden': { abbr: 'DYD', primary: '#000000', secondary: '#FFD700', text: W },
  'Dynamo Kyiv': { abbr: 'DYK', primary: '#004C99', secondary: '#FFFFFF', text: W },
  'Eintracht Frankfurt': { abbr: 'SGE', primary: '#000000', secondary: '#E1000F', text: W },
  'FC Copenhagen': { abbr: 'FCK', primary: '#122A5B', secondary: '#FFFFFF', text: W },
  Fenerbahçe: { abbr: 'FEN', primary: '#003DA5', secondary: '#FFED00', text: W },
  Feyenoord: { abbr: 'FEY', primary: '#E20E0E', secondary: '#000000', text: W },
  Fiorentina: { abbr: 'FIO', primary: '#592C82', secondary: '#FFFFFF', text: W },
  Galatasaray: { abbr: 'GAL', primary: '#A90432', secondary: '#FCC200', text: W },
  Gent: { abbr: 'GEN', primary: '#00A0DF', secondary: '#000000', text: W },
  'Hajduk Split': { abbr: 'HAJ', primary: '#0080C8', secondary: '#FFFFFF', text: W },
  Hamburg: { abbr: 'HSV', primary: '#003DA5', secondary: '#000000', text: W },
  'IFK Göteborg': { abbr: 'IFK', primary: '#003DA5', secondary: '#FFFFFF', text: W },
  'Inter Milan': { abbr: 'INT', primary: '#0068A8', secondary: '#000000', text: W },
  Juventus: { abbr: 'JUV', primary: '#000000', secondary: '#FFFFFF', text: W },
  Kaiserslautern: { abbr: 'FCK', primary: '#E30613', secondary: '#FFFFFF', text: W },
  Kuusysi: { abbr: 'KUU', primary: '#009639', secondary: '#FFFFFF', text: W },
  Lazio: { abbr: 'LAZ', primary: '#87D8F7', secondary: '#0A2240', text: '#0A2240' },
  'Leeds United': { abbr: 'LEE', primary: '#FFFFFF', secondary: '#1D428A', text: '#1D428A' },
  'Legia Warsaw': { abbr: 'LEG', primary: '#00794C', secondary: '#000000', text: W },
  'Leicester City': { abbr: 'LEI', primary: '#003090', secondary: '#FDBE11', text: W },
  Lille: { abbr: 'LIL', primary: '#E01E13', secondary: '#0A2240', text: W },
  Liverpool: { abbr: 'LIV', primary: '#C8102E', secondary: '#00B2A9', text: W },
  'Lokomotiv Moscow': { abbr: 'LOK', primary: '#008C3A', secondary: '#E30613', text: W },
  Lyon: { abbr: 'LYO', primary: '#003DA5', secondary: '#E30613', text: W },
  'Manchester City': { abbr: 'MCI', primary: '#6CABDD', secondary: '#1C2C5B', text: W },
  'Manchester United': { abbr: 'MUN', primary: '#DA291C', secondary: '#FBE122', text: W },
  Marseille: { abbr: 'OM', primary: '#2FAEE0', secondary: '#FFFFFF', text: W },
  Mechelen: { abbr: 'MEC', primary: '#FCD200', secondary: '#E30613', text: '#000000' },
  Monaco: { abbr: 'MON', primary: '#E51B22', secondary: '#FFFFFF', text: W },
  Málaga: { abbr: 'MAL', primary: '#0080C8', secondary: '#FFFFFF', text: W },
  Nantes: { abbr: 'NAN', primary: '#FDE100', secondary: '#008C3A', text: '#000000' },
  Napoli: { abbr: 'NAP', primary: '#12A0D7', secondary: '#003C82', text: W },
  'Newcastle United': { abbr: 'NEW', primary: '#241F20', secondary: '#FFFFFF', text: W },
  'Nottingham Forest': { abbr: 'NFO', primary: '#DD0000', secondary: '#FFFFFF', text: W },
  Olympiacos: { abbr: 'OLY', primary: '#E30613', secondary: '#FFFFFF', text: W },
  'PSV Eindhoven': { abbr: 'PSV', primary: '#EE2E24', secondary: '#FFFFFF', text: W },
  Panathinaikos: { abbr: 'PAN', primary: '#007A33', secondary: '#FFFFFF', text: W },
  'Paris Saint-Germain': { abbr: 'PSG', primary: '#004170', secondary: '#DA291C', text: W },
  Porto: { abbr: 'POR', primary: '#00579C', secondary: '#FFFFFF', text: W },
  'RB Leipzig': { abbr: 'RBL', primary: '#DD0741', secondary: '#001F47', text: W },
  'RB Salzburg': { abbr: 'RBS', primary: '#D81E05', secondary: '#001F47', text: W },
  Rangers: { abbr: 'RAN', primary: '#1B458F', secondary: '#E30613', text: W },
  'Rapid Wien': { abbr: 'RAP', primary: '#008C3A', secondary: '#FFFFFF', text: W },
  'Real Madrid': { abbr: 'RMA', primary: '#FEBE10', secondary: '#00529F', text: '#00529F' },
  'Real Sociedad': { abbr: 'RSO', primary: '#0067B1', secondary: '#FFFFFF', text: W },
  'Red Star Belgrade': { abbr: 'RSB', primary: '#DA291C', secondary: '#FFFFFF', text: W },
  Roma: { abbr: 'ROM', primary: '#8E1F2F', secondary: '#F0BC42', text: W },
  Rosenborg: { abbr: 'ROS', primary: '#000000', secondary: '#FFFFFF', text: W },
  Sampdoria: { abbr: 'SAM', primary: '#1B449C', secondary: '#E30613', text: W },
  'Schalke 04': { abbr: 'S04', primary: '#004D9D', secondary: '#FFFFFF', text: W },
  Sevilla: { abbr: 'SEV', primary: '#D81920', secondary: '#FFFFFF', text: W },
  'Shakhtar Donetsk': { abbr: 'SHK', primary: '#F68C1E', secondary: '#000000', text: W },
  'Sparta Prague': { abbr: 'SPA', primary: '#9C2135', secondary: '#FFD700', text: W },
  'Spartak Moscow': { abbr: 'SPM', primary: '#E30613', secondary: '#FFFFFF', text: W },
  'Sporting CP': { abbr: 'SCP', primary: '#008057', secondary: '#FFFFFF', text: W },
  'Steaua București': { abbr: 'STE', primary: '#E30613', secondary: '#003DA5', text: W },
  Strasbourg: { abbr: 'STR', primary: '#0099D8', secondary: '#FFFFFF', text: W },
  'Tottenham Hotspur': { abbr: 'TOT', primary: '#132257', secondary: '#FFFFFF', text: W },
  'Universitatea Craiova': { abbr: 'UCR', primary: '#00529F', secondary: '#E30613', text: W },
  Valencia: { abbr: 'VAL', primary: '#F18E00', secondary: '#000000', text: W },
  'VfB Stuttgart': { abbr: 'VFB', primary: '#E30613', secondary: '#FFFFFF', text: W },
  Villarreal: { abbr: 'VIL', primary: '#FFE667', secondary: '#005187', text: '#005187' },
  'Werder Bremen': { abbr: 'SVW', primary: '#1D9053', secondary: '#FFFFFF', text: W },
  'Widzew Łódź': { abbr: 'WID', primary: '#E30613', secondary: '#FFFFFF', text: W },
  Wolfsburg: { abbr: 'WOB', primary: '#65B32E', secondary: '#000000', text: W },
  'Zenit Saint Petersburg': { abbr: 'ZEN', primary: '#0072CE', secondary: '#00529F', text: W },
};

// National teams (World Cup / Euros), incl. historical sides. Colors approximate flags.
export const NATIONAL_STYLES: Record<string, TeamStyle> = {
  Algeria: { abbr: 'ALG', primary: '#006233', secondary: '#D21034', text: W },
  Argentina: { abbr: 'ARG', primary: '#75AADB', secondary: '#FFFFFF', text: W },
  Australia: { abbr: 'AUS', primary: '#00843D', secondary: '#FFCD00', text: W },
  Austria: { abbr: 'AUT', primary: '#ED2939', secondary: '#FFFFFF', text: W },
  Belgium: { abbr: 'BEL', primary: '#E30613', secondary: '#FDDA24', text: W },
  Brazil: { abbr: 'BRA', primary: '#009C3B', secondary: '#FFDF00', text: W },
  Bulgaria: { abbr: 'BUL', primary: '#00966E', secondary: '#D62612', text: W },
  Cameroon: { abbr: 'CMR', primary: '#007A5E', secondary: '#CE1126', text: W },
  Chile: { abbr: 'CHI', primary: '#0039A6', secondary: '#D52B1E', text: W },
  Colombia: { abbr: 'COL', primary: '#FCD116', secondary: '#003893', text: '#000000' },
  'Costa Rica': { abbr: 'CRC', primary: '#002B7F', secondary: '#CE1126', text: W },
  Croatia: { abbr: 'CRO', primary: '#FF0000', secondary: '#171796', text: W },
  Cuba: { abbr: 'CUB', primary: '#002A8F', secondary: '#CF142B', text: W },
  'Czech Republic': { abbr: 'CZE', primary: '#11457E', secondary: '#D7141A', text: W },
  Czechoslovakia: { abbr: 'TCH', primary: '#11457E', secondary: '#D7141A', text: W },
  Denmark: { abbr: 'DEN', primary: '#C60C30', secondary: '#FFFFFF', text: W },
  'Dutch East Indies': { abbr: 'DEI', primary: '#E70011', secondary: '#FFFFFF', text: W },
  Ecuador: { abbr: 'ECU', primary: '#FFDD00', secondary: '#034EA2', text: '#000000' },
  Egypt: { abbr: 'EGY', primary: '#CE1126', secondary: '#000000', text: W },
  England: { abbr: 'ENG', primary: '#FFFFFF', secondary: '#CE1124', text: '#CE1124' },
  'FR Yugoslavia': { abbr: 'YUG', primary: '#0C4076', secondary: '#C6363C', text: W },
  France: { abbr: 'FRA', primary: '#002395', secondary: '#ED2939', text: W },
  Georgia: { abbr: 'GEO', primary: '#FF0000', secondary: '#FFFFFF', text: W },
  Germany: { abbr: 'GER', primary: '#000000', secondary: '#DD0000', text: W },
  Ghana: { abbr: 'GHA', primary: '#006B3F', secondary: '#CE1126', text: W },
  Greece: { abbr: 'GRE', primary: '#0D5EAF', secondary: '#FFFFFF', text: W },
  Hungary: { abbr: 'HUN', primary: '#CD2A3E', secondary: '#436F4D', text: W },
  Iceland: { abbr: 'ISL', primary: '#02529C', secondary: '#DC1E35', text: W },
  Italy: { abbr: 'ITA', primary: '#0066A6', secondary: '#FFFFFF', text: W },
  Japan: { abbr: 'JPN', primary: '#BC002D', secondary: '#FFFFFF', text: W },
  Mexico: { abbr: 'MEX', primary: '#006847', secondary: '#CE1126', text: W },
  Morocco: { abbr: 'MAR', primary: '#C1272D', secondary: '#006233', text: W },
  Netherlands: { abbr: 'NED', primary: '#F36C21', secondary: '#21468B', text: W },
  Nigeria: { abbr: 'NGA', primary: '#008751', secondary: '#FFFFFF', text: W },
  'North Korea': { abbr: 'PRK', primary: '#024FA2', secondary: '#ED1C27', text: W },
  'Northern Ireland': { abbr: 'NIR', primary: '#00843D', secondary: '#FFFFFF', text: W },
  Norway: { abbr: 'NOR', primary: '#BA0C2F', secondary: '#00205B', text: W },
  Paraguay: { abbr: 'PAR', primary: '#D52B1E', secondary: '#0038A8', text: W },
  Peru: { abbr: 'PER', primary: '#D91023', secondary: '#FFFFFF', text: W },
  Poland: { abbr: 'POL', primary: '#DC143C', secondary: '#FFFFFF', text: W },
  Portugal: { abbr: 'POR', primary: '#046A38', secondary: '#DA291C', text: W },
  'Republic of Ireland': { abbr: 'IRL', primary: '#169B62', secondary: '#FF883E', text: W },
  Romania: { abbr: 'ROU', primary: '#002B7F', secondary: '#FCD116', text: W },
  Russia: { abbr: 'RUS', primary: '#0039A6', secondary: '#D52B1E', text: W },
  'Saudi Arabia': { abbr: 'KSA', primary: '#006C35', secondary: '#FFFFFF', text: W },
  Senegal: { abbr: 'SEN', primary: '#00853F', secondary: '#FDEF42', text: W },
  Slovakia: { abbr: 'SVK', primary: '#0B4EA2', secondary: '#EE1C25', text: W },
  Slovenia: { abbr: 'SVN', primary: '#005DA4', secondary: '#ED1C24', text: W },
  'South Korea': { abbr: 'KOR', primary: '#0047A0', secondary: '#CD2E3A', text: W },
  'Soviet Union': { abbr: 'URS', primary: '#CC0000', secondary: '#FFD700', text: W },
  Spain: { abbr: 'ESP', primary: '#AA151B', secondary: '#F1BF00', text: W },
  Sweden: { abbr: 'SWE', primary: '#006AA7', secondary: '#FECC00', text: W },
  Switzerland: { abbr: 'SUI', primary: '#D52B1E', secondary: '#FFFFFF', text: W },
  Turkey: { abbr: 'TUR', primary: '#E30A17', secondary: '#FFFFFF', text: W },
  Ukraine: { abbr: 'UKR', primary: '#0057B7', secondary: '#FFD700', text: W },
  'United States': { abbr: 'USA', primary: '#0A3161', secondary: '#B31942', text: W },
  Uruguay: { abbr: 'URU', primary: '#0038A8', secondary: '#FFFFFF', text: W },
  Wales: { abbr: 'WAL', primary: '#C8102E', secondary: '#00B140', text: W },
  'West Germany': { abbr: 'FRG', primary: '#000000', secondary: '#DD0000', text: W },
  Yugoslavia: { abbr: 'YUG', primary: '#0C4076', secondary: '#C6363C', text: W },
};

const FALLBACK: TeamStyle = { abbr: '???', primary: '#33404F', secondary: '#5F6B7C', text: W };

function stylesFor(league: League): Record<string, TeamStyle> {
  if (league === 'ucl') return FOOTBALL_STYLES;
  if (league === 'wc' || league === 'euro') return NATIONAL_STYLES;
  return TEAM_STYLES;
}

export function teamStyle(league: League, team: string): TeamStyle {
  return stylesFor(league)[team] ?? { ...FALLBACK, abbr: team.slice(0, 3).toUpperCase() };
}

// ESPN slug overrides where the public CDN uses a non-standard code.
const ESPN_SLUG: Record<string, string> = {
  'New Orleans Pelicans': 'no',
  'Utah Jazz': 'utah',
};

// Defunct/relocated franchises the ESPN CDN has no logo for — bundled locally instead.
const BUNDLED_LOGOS: Record<string, string> = {
  'Charlotte Bobcats': bobcatsLogo,
  'Kansas City Kings': kcKingsLogo,
  'New Orleans Hornets': noHornetsLogo,
  'Seattle SuperSonics': sonicsLogo,
  'Washington Bullets': bulletsLogo,
};

// UEFA Champions League clubs -> ESPN soccer team IDs (public CDN: /teamlogos/soccer/500/{id}.png).
// 4 defunct/obscure clubs (BFC Dynamo, Baník Ostrava, Kuusysi, Widzew Łódź) have no ESPN logo -> colored crest.
const UCL_ESPN_ID: Record<string, string> = {
  'AC Milan': '103',
  APOEL: '2497',
  Aberdeen: '263',
  Ajax: '139',
  Anderlecht: '441',
  Arsenal: '359',
  'Aston Villa': '362',
  Atalanta: '105',
  'Atlético Madrid': '1068',
  'Austria Wien': '1382',
  Auxerre: '172',
  Barcelona: '83',
  Basel: '989',
  'Bayer Leverkusen': '131',
  'Bayern Munich': '132',
  Benfica: '1929',
  Beşiktaş: '1895',
  'Bodø/Glimt': '2980',
  Bordeaux: '159',
  'Borussia Dortmund': '124',
  'Borussia Mönchengladbach': '268',
  Brøndby: '575',
  'CSKA Moscow': '1963',
  'CSKA Sofia': '10834',
  'Celta Vigo': '85',
  Celtic: '256',
  Chelsea: '363',
  'Club Brugge': '570',
  Copenhagen: '909',
  'Deportivo La Coruña': '90',
  'Dinamo București': '2496',
  'Dinamo Minsk': '2539',
  Dnipro: '21633',
  'Dundee United': '264',
  'Dynamo Dresden': '7017',
  'Dynamo Kyiv': '440',
  'Eintracht Frankfurt': '125',
  'FC Copenhagen': '909',
  Fenerbahçe: '436',
  Feyenoord: '142',
  Fiorentina: '109',
  Galatasaray: '432',
  Gent: '202',
  'Hajduk Split': '489',
  Hamburg: '127',
  'IFK Göteborg': '2556',
  'Inter Milan': '110',
  Juventus: '111',
  Kaiserslautern: '130',
  Lazio: '112',
  'Leeds United': '357',
  'Legia Warsaw': '555',
  'Leicester City': '375',
  Lille: '166',
  Liverpool: '364',
  'Lokomotiv Moscow': '442',
  Lyon: '167',
  'Manchester City': '382',
  'Manchester United': '360',
  Marseille: '176',
  Mechelen: '7879',
  Monaco: '174',
  Málaga: '99',
  Nantes: '165',
  Napoli: '114',
  'Newcastle United': '361',
  'Nottingham Forest': '393',
  Olympiacos: '435',
  'PSV Eindhoven': '148',
  Panathinaikos: '443',
  'Paris Saint-Germain': '160',
  Porto: '437',
  'RB Leipzig': '11420',
  'RB Salzburg': '2790',
  Rangers: '257',
  'Rapid Wien': '519',
  'Real Madrid': '86',
  'Real Sociedad': '89',
  'Red Star Belgrade': '2290',
  Roma: '21685',
  Rosenborg: '438',
  Sampdoria: '2734',
  'Schalke 04': '133',
  Sevilla: '243',
  'Shakhtar Donetsk': '493',
  'Sparta Prague': '433',
  'Spartak Moscow': '1941',
  'Sporting CP': '2250',
  'Steaua București': '484',
  Strasbourg: '180',
  'Tottenham Hotspur': '367',
  'Universitatea Craiova': '8089',
  Valencia: '94',
  'VfB Stuttgart': '134',
  Villarreal: '102',
  'Werder Bremen': '137',
  Wolfsburg: '138',
  'Zenit Saint Petersburg': '2533',
};

// National teams -> ESPN soccer team IDs. 5 defunct nations (Czechoslovakia, Dutch East Indies,
// FR Yugoslavia, Soviet Union, Yugoslavia) have no ESPN logo -> colored crest fallback.
const NATIONAL_ESPN_ID: Record<string, string> = {
  Algeria: '624',
  Argentina: '202',
  Australia: '628',
  Austria: '474',
  Belgium: '459',
  Brazil: '205',
  Bulgaria: '462',
  Cameroon: '656',
  Chile: '207',
  Colombia: '208',
  'Costa Rica': '214',
  Croatia: '477',
  Cuba: '2647',
  'Czech Republic': '450',
  Denmark: '479',
  Ecuador: '209',
  Egypt: '2620',
  England: '448',
  France: '478',
  Georgia: '584',
  Germany: '481',
  Ghana: '4469',
  Greece: '455',
  Hungary: '480',
  Iceland: '470',
  Italy: '162',
  Japan: '627',
  Mexico: '203',
  Morocco: '2869',
  Netherlands: '449',
  Nigeria: '657',
  'North Korea': '2759',
  'Northern Ireland': '586',
  Norway: '464',
  Paraguay: '210',
  Peru: '211',
  Poland: '471',
  Portugal: '482',
  'Republic of Ireland': '476',
  Romania: '473',
  Russia: '454',
  'Saudi Arabia': '655',
  Senegal: '654',
  Slovakia: '468',
  Slovenia: '472',
  'South Korea': '451',
  Spain: '164',
  Sweden: '466',
  Switzerland: '475',
  Turkey: '465',
  Ukraine: '457',
  'United States': '660',
  Uruguay: '212',
  Wales: '578',
  'West Germany': '481',
};

// Runtime logo URL from a public CDN, or null to signal "use the colored crest".
// A handful of defunct clubs/franchises have no CDN logo -> null triggers the crest fallback in TeamLogo.
export function logoUrl(league: League, team: string): string | null {
  if (league === 'ucl') {
    const id = UCL_ESPN_ID[team];
    return id ? `https://a.espncdn.com/i/teamlogos/soccer/500/${id}.png` : null;
  }
  if (league === 'wc' || league === 'euro') {
    const id = NATIONAL_ESPN_ID[team];
    return id ? `https://a.espncdn.com/i/teamlogos/soccer/500/${id}.png` : null;
  }
  if (BUNDLED_LOGOS[team]) return BUNDLED_LOGOS[team];
  const style = TEAM_STYLES[team];
  if (!style) return null;
  const slug = ESPN_SLUG[team] ?? style.abbr.toLowerCase();
  return `https://a.espncdn.com/i/teamlogos/nba/500/${slug}.png`;
}

// Short display names for the longest football clubs; NBA drops the city.
const FOOTBALL_SHORT: Record<string, string> = {
  'Manchester United': 'Man United',
  'Manchester City': 'Man City',
  'Borussia Mönchengladbach': "M'gladbach",
  'Borussia Dortmund': 'Dortmund',
  'Paris Saint-Germain': 'PSG',
  'Tottenham Hotspur': 'Tottenham',
  'Zenit Saint Petersburg': 'Zenit',
  'Deportivo La Coruña': 'Deportivo',
  'Red Star Belgrade': 'Red Star',
  'Universitatea Craiova': 'U. Craiova',
  'Bayer Leverkusen': 'Leverkusen',
  'Eintracht Frankfurt': 'Frankfurt',
  'Newcastle United': 'Newcastle',
  'Leicester City': 'Leicester',
  'Leeds United': 'Leeds',
  'Dundee United': 'Dundee Utd',
};

// Short display names for the longest national sides; keeps cards readable.
const NATIONAL_SHORT: Record<string, string> = {
  'United States': 'USA',
  'Republic of Ireland': 'Ireland',
  'Northern Ireland': 'N. Ireland',
  'Czech Republic': 'Czechia',
};

export function shortName(league: League, team: string): string {
  if (league === 'ucl') return FOOTBALL_SHORT[team] ?? team;
  if (league === 'wc' || league === 'euro') return NATIONAL_SHORT[team] ?? team;
  const parts = team.split(' ');
  return parts.length > 1 ? parts[parts.length - 1] : team;
}
