import type { OrbitTarget } from '../globe/camera';

export type VoyagerStop = OrbitTarget & {
  readonly id: string;
  readonly title: string;
  readonly subtitle: string;
  readonly description: string;
};

export type VoyagerTour = {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly stops: readonly string[];
};

// Heights are approximate ellipsoid heights of the focus point (meters).
export const VOYAGER_STOPS: readonly VoyagerStop[] = [
  {
    id: 'eiffel',
    title: 'Eiffel Tower',
    subtitle: 'Paris, France',
    description: 'Gustave Eiffel’s wrought-iron lattice tower, built for the 1889 World’s Fair.',
    lat: 48.8584,
    lon: 2.2945,
    height: 150,
    range: 900,
    heading: 30,
    pitch: -25,
  },
  {
    id: 'colosseum',
    title: 'Colosseum',
    subtitle: 'Rome, Italy',
    description: 'The largest ancient amphitheatre ever built, completed in 80 AD.',
    lat: 41.8902,
    lon: 12.4922,
    height: 80,
    range: 500,
    heading: 20,
    pitch: -35,
  },
  {
    id: 'sagrada',
    title: 'Sagrada Família',
    subtitle: 'Barcelona, Spain',
    description: 'Gaudí’s unfinished basilica, under construction since 1882.',
    lat: 41.4036,
    lon: 2.1744,
    height: 150,
    range: 450,
    heading: 160,
    pitch: -25,
  },
  {
    id: 'big-ben',
    title: 'Westminster',
    subtitle: 'London, United Kingdom',
    description: 'The Houses of Parliament and the Elizabeth Tower on the Thames.',
    lat: 51.5007,
    lon: -0.1246,
    height: 100,
    range: 700,
    heading: 250,
    pitch: -25,
  },
  {
    id: 'acropolis',
    title: 'Acropolis',
    subtitle: 'Athens, Greece',
    description: 'The ancient citadel crowned by the Parthenon, 5th century BC.',
    lat: 37.9715,
    lon: 23.7257,
    height: 190,
    range: 650,
    heading: 340,
    pitch: -25,
  },
  {
    id: 'santorini',
    title: 'Oia',
    subtitle: 'Santorini, Greece',
    description: 'White-washed village on the rim of a flooded volcanic caldera.',
    lat: 36.4618,
    lon: 25.3753,
    height: 130,
    range: 1300,
    heading: 250,
    pitch: -20,
  },
  {
    id: 'old-city',
    title: 'Old City of Jerusalem',
    subtitle: 'Jerusalem',
    description: 'Walled city holy to three religions, home to the Dome of the Rock.',
    lat: 31.7781,
    lon: 35.2354,
    height: 790,
    range: 900,
    heading: 90,
    pitch: -30,
  },
  {
    id: 'tel-aviv',
    title: 'Tel Aviv Coastline',
    subtitle: 'Tel Aviv, Israel',
    description: 'The White City’s Mediterranean beaches and Bauhaus skyline.',
    lat: 32.0809,
    lon: 34.7681,
    height: 40,
    range: 2800,
    heading: 80,
    pitch: -25,
  },
  {
    id: 'petra',
    title: 'Petra',
    subtitle: 'Ma’an, Jordan',
    description: 'The Nabataean city carved into rose-red sandstone cliffs.',
    lat: 30.3285,
    lon: 35.4444,
    height: 960,
    range: 900,
    heading: 200,
    pitch: -30,
  },
  {
    id: 'pyramids',
    title: 'Pyramids of Giza',
    subtitle: 'Giza, Egypt',
    description: 'The last standing wonder of the ancient world, about 4,500 years old.',
    lat: 29.9773,
    lon: 31.1325,
    height: 160,
    range: 2200,
    heading: 45,
    pitch: -25,
  },
  {
    id: 'burj',
    title: 'Burj Khalifa',
    subtitle: 'Dubai, UAE',
    description: 'At 828 m, the tallest structure ever built.',
    lat: 25.1972,
    lon: 55.2744,
    height: 500,
    range: 1800,
    heading: 300,
    pitch: -15,
  },
  {
    id: 'taj',
    title: 'Taj Mahal',
    subtitle: 'Agra, India',
    description: 'Shah Jahan’s white-marble mausoleum on the Yamuna river.',
    lat: 27.1751,
    lon: 78.0421,
    height: 150,
    range: 700,
    heading: 0,
    pitch: -25,
  },
  {
    id: 'everest',
    title: 'Mount Everest',
    subtitle: 'Nepal / China',
    description: 'Earth’s highest mountain above sea level, 8,849 m.',
    lat: 27.9881,
    lon: 86.925,
    height: 8800,
    range: 14000,
    heading: 200,
    pitch: -20,
  },
  {
    id: 'great-wall',
    title: 'Great Wall at Mutianyu',
    subtitle: 'Beijing, China',
    description: 'A restored section of the wall snaking across forested ridges.',
    lat: 40.4319,
    lon: 116.5704,
    height: 600,
    range: 1500,
    heading: 40,
    pitch: -25,
  },
  {
    id: 'fuji',
    title: 'Mount Fuji',
    subtitle: 'Honshu, Japan',
    description: 'Japan’s iconic, nearly symmetrical stratovolcano.',
    lat: 35.3606,
    lon: 138.7274,
    height: 3700,
    range: 16000,
    heading: 340,
    pitch: -18,
  },
  {
    id: 'tokyo',
    title: 'Shibuya Crossing',
    subtitle: 'Tokyo, Japan',
    description: 'One of the busiest pedestrian crossings in the world.',
    lat: 35.6595,
    lon: 139.7005,
    height: 80,
    range: 600,
    heading: 120,
    pitch: -35,
  },
  {
    id: 'angkor',
    title: 'Angkor Wat',
    subtitle: 'Siem Reap, Cambodia',
    description: 'The largest religious monument in the world, built in the 12th century.',
    lat: 13.4125,
    lon: 103.867,
    height: 60,
    range: 2200,
    heading: 270,
    pitch: -30,
  },
  {
    id: 'singapore',
    title: 'Marina Bay',
    subtitle: 'Singapore',
    description: 'Marina Bay Sands and the Gardens by the Bay supertrees.',
    lat: 1.2834,
    lon: 103.8607,
    height: 60,
    range: 2200,
    heading: 280,
    pitch: -22,
  },
  {
    id: 'opera',
    title: 'Sydney Opera House',
    subtitle: 'Sydney, Australia',
    description: 'Jørn Utzon’s sail-shaped performing arts centre on the harbour.',
    lat: -33.8568,
    lon: 151.2153,
    height: 30,
    range: 750,
    heading: 130,
    pitch: -25,
  },
  {
    id: 'uluru',
    title: 'Uluru',
    subtitle: 'Northern Territory, Australia',
    description: 'A sacred sandstone monolith rising 348 m above the desert.',
    lat: -25.3444,
    lon: 131.0369,
    height: 850,
    range: 9000,
    heading: 20,
    pitch: -20,
  },
  {
    id: 'kilimanjaro',
    title: 'Kilimanjaro',
    subtitle: 'Tanzania',
    description: 'Africa’s highest peak, a dormant volcano with a glaciated summit.',
    lat: -3.0674,
    lon: 37.3556,
    height: 5800,
    range: 18000,
    heading: 180,
    pitch: -20,
  },
  {
    id: 'table-mountain',
    title: 'Table Mountain',
    subtitle: 'Cape Town, South Africa',
    description: 'The flat-topped mountain overlooking Cape Town and the Atlantic.',
    lat: -33.9628,
    lon: 18.4098,
    height: 1050,
    range: 7000,
    heading: 160,
    pitch: -20,
  },
  {
    id: 'victoria-falls',
    title: 'Victoria Falls',
    subtitle: 'Zambia / Zimbabwe',
    description: '“The Smoke That Thunders”, the largest sheet of falling water on Earth.',
    lat: -17.9243,
    lon: 25.8572,
    height: 900,
    range: 3000,
    heading: 60,
    pitch: -30,
  },
  {
    id: 'rio',
    title: 'Christ the Redeemer',
    subtitle: 'Rio de Janeiro, Brazil',
    description: 'The Art Deco statue atop Corcovado, overlooking Guanabara Bay.',
    lat: -22.9519,
    lon: -43.2105,
    height: 700,
    range: 1500,
    heading: 120,
    pitch: -15,
  },
  {
    id: 'machu-picchu',
    title: 'Machu Picchu',
    subtitle: 'Cusco Region, Peru',
    description: 'A 15th-century Inca citadel on a ridge high in the Andes.',
    lat: -13.1631,
    lon: -72.545,
    height: 2450,
    range: 1600,
    heading: 330,
    pitch: -25,
  },
  {
    id: 'grand-canyon',
    title: 'Grand Canyon',
    subtitle: 'Arizona, USA',
    description: 'The Colorado River’s mile-deep canyon through two billion years of rock.',
    lat: 36.0997,
    lon: -112.1124,
    height: 1800,
    range: 12000,
    heading: 20,
    pitch: -20,
  },
  {
    id: 'golden-gate',
    title: 'Golden Gate Bridge',
    subtitle: 'San Francisco, USA',
    description: 'The International Orange suspension bridge at the mouth of the bay.',
    lat: 37.8199,
    lon: -122.4783,
    height: 100,
    range: 2800,
    heading: 140,
    pitch: -18,
  },
  {
    id: 'yosemite',
    title: 'Half Dome',
    subtitle: 'Yosemite, USA',
    description: 'The granite dome rising 1,444 m above Yosemite Valley.',
    lat: 37.7459,
    lon: -119.5332,
    height: 2650,
    range: 7000,
    heading: 60,
    pitch: -18,
  },
  {
    id: 'manhattan',
    title: 'Lower Manhattan',
    subtitle: 'New York, USA',
    description: 'The skyline of the Financial District and One World Trade Center.',
    lat: 40.7127,
    lon: -74.0134,
    height: 250,
    range: 2600,
    heading: 30,
    pitch: -20,
  },
  {
    id: 'niagara',
    title: 'Niagara Falls',
    subtitle: 'Ontario / New York',
    description: 'Three waterfalls straddling the US–Canada border.',
    lat: 43.0799,
    lon: -79.0747,
    height: 150,
    range: 2200,
    heading: 200,
    pitch: -25,
  },
  {
    id: 'chichen-itza',
    title: 'Chichén Itzá',
    subtitle: 'Yucatán, Mexico',
    description: 'The Maya pyramid of El Castillo and its surrounding city.',
    lat: 20.6843,
    lon: -88.5678,
    height: 30,
    range: 600,
    heading: 45,
    pitch: -30,
  },
  {
    id: 'iceland',
    title: 'Jökulsárlón',
    subtitle: 'Iceland',
    description: 'A glacier lagoon filled with icebergs calving from Breiðamerkurjökull.',
    lat: 64.0784,
    lon: -16.2306,
    height: 70,
    range: 6000,
    heading: 0,
    pitch: -25,
  },
];

export const VOYAGER_TOURS: readonly VoyagerTour[] = [
  {
    id: 'wonders',
    title: 'Wonders of the World',
    description: 'Ancient and modern wonders, from Giza to Machu Picchu.',
    stops: ['pyramids', 'petra', 'colosseum', 'taj', 'great-wall', 'chichen-itza', 'machu-picchu', 'rio'],
  },
  {
    id: 'cities',
    title: 'Great Cities',
    description: 'Skylines and landmarks of the world’s great cities.',
    stops: ['manhattan', 'big-ben', 'eiffel', 'sagrada', 'tel-aviv', 'burj', 'tokyo', 'singapore', 'opera'],
  },
  {
    id: 'nature',
    title: 'Natural Marvels',
    description: 'Mountains, canyons and waterfalls.',
    stops: ['everest', 'fuji', 'kilimanjaro', 'victoria-falls', 'grand-canyon', 'yosemite', 'uluru', 'iceland', 'niagara'],
  },
  {
    id: 'mediterranean',
    title: 'Around the Mediterranean',
    description: 'From the Aegean islands to the Levant.',
    stops: ['santorini', 'acropolis', 'old-city', 'tel-aviv', 'pyramids', 'colosseum', 'sagrada'],
  },
];

export const stopById = (id: string): VoyagerStop | undefined => VOYAGER_STOPS.find((s) => s.id === id);
